# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dashboard_window(object):
    def setupUi(self, dashboard_window):
        dashboard_window.setObjectName("dashboard_window")
        dashboard_window.resize(1266, 813)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/cg_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dashboard_window.setWindowIcon(icon)
        dashboard_window.setStyleSheet("*{\n"
"    font-family: Century Gothic;\n"
"}\n"
"\n"
"QGroupBox{\n"
"    background-color:#333;\n"
"    color: #fff;\n"
"    border-radius: 5px;\n"
"    border: 1px solid gray;\n"
"    font: 14pt \"Montserrat\";\n"
"}\n"
"\n"
"/*QLabel{\n"
"    color: white;\n"
"}*/\n"
"\n"
"QToolButton{\n"
"    border-radius: 40px;\n"
"    background-color:orange;\n"
"    border: 5px solid #333;\n"
"}\n"
"\n"
"/*** QLineEdit ***/\n"
"QLineEdit{\n"
"    font: 10pt \"Montserrat\";\n"
"    color: rgb(0, 1, 146);\n"
"    padding: 10px;\n"
"/*    background-color: rgb(186, 209, 248);*/\n"
"}\n"
"\n"
"\n"
"/**** QSpinBox ****/\n"
"QSpinBox {\n"
"    background-color: rgb(186, 209, 248); /* Couleur d\'arrière-plan */\n"
"    color: rgb(0, 1, 146);                /* Couleur du texte */\n"
"    border: 1px outset gray;     /* Bordure */\n"
"    box-shadow: outset 5px 5px 10px gray;\n"
"    border-radius: 1px;                   /* Coins arrondis */\n"
"    padding: 10px;                         /* Espacement interne */\n"
"    border-bottom: 1px outset gray;\n"
"}\n"
"\n"
"QSpinBox::up-button, QSpinBox::down-button {\n"
"   /*background-color: transparent;        /* Rendre les boutons transparents pour voir la couleur de fond */\n"
"    border: none;                         /* Supprime les bordures des boutons */\n"
"    width: 20px;                          /* Largeur des boutons */\n"
"}\n"
"\n"
"QSpinBox::up-arrow, QSpinBox::down-arrow {\n"
"    width: 10px;                          /* Taille des flèches */\n"
"    height: 10px;\n"
"    background: rgb(0, 1, 146);                     /* Supprime les fonds des flèches */\n"
"    color: white;                /* Couleur des flèches */\n"
"}\n"
"\n"
"QSpinBox:focus {\n"
"    border: 1px solid rgb(65, 173, 255);   /* Bordure différente en cas de focus */\n"
"}\n"
"\n"
"/******************************/\n"
"\n"
"\n"
"\n"
"QRadioButton{\n"
"    color: rgb(51, 51, 51);\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"\n"
"/**** QComboBox ****/\n"
"QComboBox {\n"
"    font: 10pt \"Montserrat\";\n"
"    /*background-color: rgb(186, 209, 248);*/\n"
"    color: rgb(0, 1, 146);\n"
"    padding: 10px;\n"
"    /*box-shadow: none;\n"
"    border: none;*/\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none; /* Supprime la bordure du bouton de la flèche */\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: rgb(186, 209, 248); /* Couleur de fond du menu déroulant */\n"
"    color: rgb(0, 1, 146);               /* Couleur du texte */\n"
"  /* border: 1px solid rgb(150, 150, 150); /* Bordure pour alignement avec le parent */\n"
"    font: 10pt \"Montserrat\";\n"
"   /* margin: 0 20px;                         /* Supprime les débordements */\n"
"    padding: 0 10px;\n"
"    outline: none;                    /* Supprime l\'effet de focus */\n"
"    border: none; \n"
"    box-shadow: none;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"    padding: 10px;                       /* Ajoute un espacement entre les éléments */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: rgb(150, 180, 220); /* Couleur pour l\'élément sélectionné */\n"
"    color: white;                        /* Couleur du texte pour l\'élément sélectionné */\n"
"}")
        dashboard_window.setIconSize(QtCore.QSize(16, 16))
        self.centralwidget = QtWidgets.QWidget(dashboard_window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(211, 0, 101, 91))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/cg_icon_pt.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.header_lbl_2 = QtWidgets.QLabel(self.centralwidget)
        self.header_lbl_2.setGeometry(QtCore.QRect(350, 0, 701, 91))
        self.header_lbl_2.setStyleSheet("font: 81 22pt \"Montserrat ExtraBold\";\n"
"color: rgb(0, 1, 146);\n"
"")
        self.header_lbl_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.header_lbl_2.setObjectName("header_lbl_2")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(0, 90, 1271, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(17, 105, 1231, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.user_auth_lbl = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_auth_lbl.sizePolicy().hasHeightForWidth())
        self.user_auth_lbl.setSizePolicy(sizePolicy)
        self.user_auth_lbl.setStyleSheet("background-color: rgb(0, 1, 146);\n"
"color: rgb(186, 209, 248);\n"
"padding-left: 10px;\n"
"font-size: 16px;")
        self.user_auth_lbl.setObjectName("user_auth_lbl")
        self.horizontalLayout.addWidget(self.user_auth_lbl)
        self.name_user_auth_lbl = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_user_auth_lbl.sizePolicy().hasHeightForWidth())
        self.name_user_auth_lbl.setSizePolicy(sizePolicy)
        self.name_user_auth_lbl.setStyleSheet("font-size: 16px;\n"
"color: rgba(255, 0, 0, 175);\n"
"/*color: rgb(51, 51, 51);*/\n"
"")
        self.name_user_auth_lbl.setText("")
        self.name_user_auth_lbl.setObjectName("name_user_auth_lbl")
        self.horizontalLayout.addWidget(self.name_user_auth_lbl)
        self.date_heure = QtWidgets.QDateTimeEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_heure.sizePolicy().hasHeightForWidth())
        self.date_heure.setSizePolicy(sizePolicy)
        self.date_heure.setMinimumSize(QtCore.QSize(0, 0))
        self.date_heure.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.date_heure.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.date_heure.setFont(font)
        self.date_heure.setAutoFillBackground(False)
        self.date_heure.setStyleSheet("color: rgb(0, 1, 146);\n"
"border-radius: 5px;")
        self.date_heure.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.BurkinaFaso))
        self.date_heure.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.date_heure.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.date_heure.setReadOnly(False)
        self.date_heure.setDate(QtCore.QDate(2023, 1, 1))
        self.date_heure.setCalendarPopup(True)
        self.date_heure.setObjectName("date_heure")
        self.horizontalLayout.addWidget(self.date_heure)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(0, 153, 1271, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.tw_identity = QtWidgets.QTabWidget(self.centralwidget)
        self.tw_identity.setGeometry(QtCore.QRect(9, 180, 1249, 481))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tw_identity.sizePolicy().hasHeightForWidth())
        self.tw_identity.setSizePolicy(sizePolicy)
        self.tw_identity.setStyleSheet("color: rgb(0, 1, 146);")
        self.tw_identity.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tw_identity.setUsesScrollButtons(True)
        self.tw_identity.setDocumentMode(True)
        self.tw_identity.setObjectName("tw_identity")
        self.patient_tab = QtWidgets.QWidget()
        self.patient_tab.setObjectName("patient_tab")
        self.restitute_tbl = QtWidgets.QTableWidget(self.patient_tab)
        self.restitute_tbl.setGeometry(QtCore.QRect(10, 60, 1231, 281))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.restitute_tbl.sizePolicy().hasHeightForWidth())
        self.restitute_tbl.setSizePolicy(sizePolicy)
        self.restitute_tbl.setStyleSheet("border-color: rgb(131, 171, 240);")
        self.restitute_tbl.setAutoScrollMargin(12)
        self.restitute_tbl.setColumnCount(18)
        self.restitute_tbl.setObjectName("restitute_tbl")
        self.restitute_tbl.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.restitute_tbl.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.restitute_tbl.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.restitute_tbl.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.restitute_tbl.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.restitute_tbl.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.restitute_tbl.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.restitute_tbl.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.restitute_tbl.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.restitute_tbl.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.restitute_tbl.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.restitute_tbl.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.restitute_tbl.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.restitute_tbl.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.restitute_tbl.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.restitute_tbl.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.restitute_tbl.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.restitute_tbl.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.restitute_tbl.setHorizontalHeaderItem(17, item)
        self.restitute_tbl.horizontalHeader().setCascadingSectionResizes(True)
        self.restitute_tbl.verticalHeader().setCascadingSectionResizes(True)
        self.restitute_tbl.verticalHeader().setDefaultSectionSize(30)
        self.refresh_btn = QtWidgets.QPushButton(self.patient_tab)
        self.refresh_btn.setGeometry(QtCore.QRect(1040, 360, 191, 41))
        self.refresh_btn.setStyleSheet("QPushButton{\n"
"    background-color:  rgb(25, 135, 84);\n"
"    border-radius: 3px;\n"
"    color: white;\n"
"    border: 1px inset gray;\n"
"    font: 16pt \"Century Gothic\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #adc4ad;\n"
"border-radius: 3px;\n"
"    border: 1px inset gray;\n"
"    color: black;\n"
"    font: 16pt \"Century Gothic\";\n"
"}")

        self.manage_users_btn = QtWidgets.QPushButton(self.patient_tab)
        self.manage_users_btn.setGeometry(QtCore.QRect(10, 360, 311, 41))
        self.manage_users_btn.setStyleSheet("QPushButton{\n"
                                       "    background-color:  rgb(25, 135, 84);\n"
                                       "    border-radius: 3px;\n"
                                       "    color: white;\n"
                                       "    border: 1px inset gray;\n"
                                       "    font: 16pt \"Century Gothic\";\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:hover{\n"
                                       "    background-color: #adc4ad;\n"
                                       "border-radius: 3px;\n"
                                       "    border: 1px inset gray;\n"
                                       "    color: black;\n"
                                       "    font: 16pt \"Century Gothic\";\n"
                                       "}")
        self.manage_users_btn.setObjectName("manage_users_btn")

        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.patient_tab)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(11, 10, 1231, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.search_lbl = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.search_lbl.setStyleSheet("font: 10pt \"Century Gothic\";\n"
"color: rgba(51, 51, 51);")
        self.search_lbl.setObjectName("search_lbl")
        self.horizontalLayout_3.addWidget(self.search_lbl)
        self.search_lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.search_lineEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(131, 171, 240);\n"
"")
        self.search_lineEdit.setObjectName("search_lineEdit")
        self.horizontalLayout_3.addWidget(self.search_lineEdit)
        self.search_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.search_btn.setStyleSheet("width: 150px;\n"
"height: 36px;")
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout_3.addWidget(self.search_btn)
        self.tw_identity.addTab(self.patient_tab, "")
        self.tasaisie_identite_tab = QtWidgets.QWidget()
        self.tasaisie_identite_tab.setObjectName("tasaisie_identite_tab")
        self.id_lbl = QtWidgets.QLabel(self.tasaisie_identite_tab)
        self.id_lbl.setGeometry(QtCore.QRect(11, 4, 34, 40))
        self.id_lbl.setStyleSheet("font: 12pt \"Century Gothic\";\n"
"font-weight: bold;\n"
"color: rgb(51, 51, 51);\n"
"padding-left: 10px;")
        self.id_lbl.setObjectName("id_lbl")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tasaisie_identite_tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 50, 1221, 271))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 15, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.phone_lbl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.phone_lbl.setStyleSheet("font: 12pt \"Century Gothic\";\n"
"color: rgb(51, 51, 51);\n"
"padding-left: 10px;\n"
"margin-left: 20px;")
        self.phone_lbl.setObjectName("phone_lbl")
        self.gridLayout_2.addWidget(self.phone_lbl, 2, 5, 1, 1)
        self.sector_lbl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.sector_lbl.setStyleSheet("font: 12pt \"Century Gothic\";\n"
"color: rgb(51, 51, 51);\n"
"padding-left: 10px;\n"
"margin-left: 20px;")
        self.sector_lbl.setObjectName("sector_lbl")
        self.gridLayout_2.addWidget(self.sector_lbl, 1, 5, 1, 1)
        self.profession_lbl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.profession_lbl.setStyleSheet("font: 12pt \"Century Gothic\";\n"
"color: rgb(51, 51, 51);\n"
"padding-left: 10px;")
        self.profession_lbl.setObjectName("profession_lbl")
        self.gridLayout_2.addWidget(self.profession_lbl, 1, 0, 1, 1)
        self.commune_lbl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.commune_lbl.setStyleSheet("font: 12pt \"Century Gothic\";\n"
"color: rgb(51, 51, 51);\n"
"padding-left: 10px;\n"
"margin-left: 20px;")
        self.commune_lbl.setObjectName("commune_lbl")
        self.gridLayout_2.addWidget(self.commune_lbl, 0, 5, 1, 1)
        self.name_ledit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.name_ledit.setObjectName("name_ledit")
        self.gridLayout_2.addWidget(self.name_ledit, 0, 1, 1, 1)
        self.commune_ledit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.commune_ledit.setObjectName("commune_ledit")
        self.gridLayout_2.addWidget(self.commune_ledit, 0, 6, 1, 1)
        self.profession_ledit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.profession_ledit.setObjectName("profession_ledit")
        self.gridLayout_2.addWidget(self.profession_ledit, 1, 1, 1, 1)
        self.sector_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.sector_spinBox.setObjectName("sector_spinBox")
        self.gridLayout_2.addWidget(self.sector_spinBox, 1, 6, 1, 1)
        self.age_lbl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.age_lbl.setStyleSheet("font: 12pt \"Century Gothic\";\n"
"color: rgb(51, 51, 51);\n"
"padding-left: 10px;")
        self.age_lbl.setObjectName("age_lbl")
        self.gridLayout_2.addWidget(self.age_lbl, 2, 0, 1, 1)
        self.woman_rbtn = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.woman_rbtn.setCheckable(True)
        self.woman_rbtn.setChecked(False)
        self.woman_rbtn.setObjectName("woman_rbtn")
        self.gridLayout_2.addWidget(self.woman_rbtn, 4, 1, 1, 1)
        self.gender_lbl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.gender_lbl.setStyleSheet("font: 12pt \"Century Gothic\";\n"
"color: rgb(51, 51, 51);\n"
"padding-left: 10px;")
        self.gender_lbl.setObjectName("gender_lbl")
        self.gridLayout_2.addWidget(self.gender_lbl, 4, 0, 1, 1)
        self.zone_comboBox = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.zone_comboBox.setStyleSheet("\n"
"    background-color: rgb(186, 209, 248);")
        self.zone_comboBox.setModelColumn(0)
        self.zone_comboBox.setObjectName("zone_comboBox")
        self.zone_comboBox.addItem("")
        self.zone_comboBox.addItem("")
        self.zone_comboBox.addItem("")
        self.zone_comboBox.addItem("")
        self.gridLayout_2.addWidget(self.zone_comboBox, 4, 6, 1, 1)
        self.zone_lbl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.zone_lbl.setStyleSheet("font: 12pt \"Century Gothic\";\n"
"color: rgb(51, 51, 51);\n"
"padding-left: 10px;\n"
"margin-left: 20px;")
        self.zone_lbl.setObjectName("zone_lbl")
        self.gridLayout_2.addWidget(self.zone_lbl, 4, 5, 1, 1)
        self.phone_ledit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.phone_ledit.setObjectName("phone_ledit")
        self.gridLayout_2.addWidget(self.phone_ledit, 2, 6, 1, 1)
        self.name_lbl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.name_lbl.setStyleSheet("font: 12pt \"Century Gothic\";\n"
"color: rgb(51, 51, 51);\n"
"padding-left: 10px;")
        self.name_lbl.setObjectName("name_lbl")
        self.gridLayout_2.addWidget(self.name_lbl, 0, 0, 1, 1)
        self.age_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.age_spinBox.setStyleSheet("")
        self.age_spinBox.setObjectName("age_spinBox")
        self.gridLayout_2.addWidget(self.age_spinBox, 2, 1, 1, 1)
        self.man_rbtn = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.man_rbtn.setObjectName("man_rbtn")
        self.gridLayout_2.addWidget(self.man_rbtn, 5, 1, 1, 1)
        self.record_id = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.record_id.setStyleSheet("/*background-color: rgb(0, 1, 146);\n"
"color: rgb(186, 209, 248);\n"
"font: 75 16pt \"Century Gothic\";\n"
"padding-left:5px;*/\n"
"color: transparent;\n"
"")
        self.record_id.setAlignment(QtCore.Qt.AlignCenter)
        self.record_id.setObjectName("record_id")
        self.gridLayout_2.addWidget(self.record_id, 5, 5, 1, 1)
        self.lbl_date_heure = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lbl_date_heure.setStyleSheet("border: 1px solid transparent;\n"
"")
        self.lbl_date_heure.setText("")
        self.lbl_date_heure.setObjectName("lbl_date_heure")
        self.gridLayout_2.addWidget(self.lbl_date_heure, 5, 6, 1, 1)
        self.first_btn = QtWidgets.QPushButton(self.tasaisie_identite_tab)
        self.first_btn.setGeometry(QtCore.QRect(10, 359, 51, 31))
        self.first_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 1, 146);\n"
"    border-radius: 3px;\n"
"    color: rgb(186, 209, 24);\n"
"    border: 1px outset gray;\n"
"    font: 12pt \"Century Gothic\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: orange;\n"
"    border-radius: 3px;\n"
"    border: 1px outset gray;\n"
"    font: 12pt \"Century Gothic\";\n"
"}\n"
"\n"
"")
        self.first_btn.setObjectName("first_btn")
        self.previous_btn = QtWidgets.QPushButton(self.tasaisie_identite_tab)
        self.previous_btn.setGeometry(QtCore.QRect(62, 359, 51, 31))
        self.previous_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 1, 146);\n"
"    border-radius: 3px;\n"
"    color: rgb(186, 209, 24);\n"
"    border: 1px outset gray;\n"
"    font: 12pt \"Century Gothic\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: orange;\n"
"    border-radius: 3px;\n"
"    border: 1px outset gray;\n"
"    font: 12pt \"Century Gothic\";\n"
"}\n"
"")
        self.previous_btn.setObjectName("previous_btn")
        self.last_btn = QtWidgets.QPushButton(self.tasaisie_identite_tab)
        self.last_btn.setGeometry(QtCore.QRect(182, 360, 51, 31))
        self.last_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 1, 146);\n"
"    border-radius: 3px;\n"
"    color: rgb(186, 209, 24);\n"
"    border: 1px outset gray;\n"
"    font: 12pt \"Century Gothic\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: orange;\n"
"    border-radius: 3px;\n"
"    border: 1px outset gray;\n"
"    font: 12pt \"Century Gothic\";\n"
"}\n"
"")
        self.last_btn.setObjectName("last_btn")
        self.next_btn = QtWidgets.QPushButton(self.tasaisie_identite_tab)
        self.next_btn.setGeometry(QtCore.QRect(130, 360, 51, 31))
        self.next_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 1, 146);\n"
"    border-radius: 3px;\n"
"    color: rgb(186, 209, 24);\n"
"    border: 1px outset gray;\n"
"    font: 12pt \"Century Gothic\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: orange;\n"
"    border-radius: 3px;\n"
"    border: 1px outset gray;\n"
"    font: 12pt \"Century Gothic\";\n"
"}\n"
"")
        self.next_btn.setObjectName("next_btn")
        self.add_btn = QtWidgets.QPushButton(self.tasaisie_identite_tab)
        self.add_btn.setGeometry(QtCore.QRect(639, 360, 191, 41))
        self.add_btn.setStyleSheet("QPushButton{\n"
"    background-color:  rgb(25,135,84);\n"
"    border-radius: 3px;\n"
"    color: white;\n"
"    border: 1px inset gray;\n"
"    font: 16pt \"Century Gothic\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #adc4ad;\n"
"    border-radius: 3px;\n"
"    border: 1px inset gray;\n"
"    color: black;\n"
"    font: 16pt \"Century Gothic\";\n"
"}")
        self.add_btn.setObjectName("add_btn")
        self.edit_btn = QtWidgets.QPushButton(self.tasaisie_identite_tab)
        self.edit_btn.setGeometry(QtCore.QRect(839, 360, 191, 41))
        self.edit_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(13,110,253);\n"
"    border-radius: 3px;\n"
"    color: white;\n"
"    border: 1px inset gray;\n"
"    font: 16pt \"Century Gothic\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(13,202,240);\n"
"    border-radius: 3px;\n"
"    border: 1px inset gray;\n"
"    color: black;\n"
"    font: 16pt \"Century Gothic\";\n"
"}")
        self.edit_btn.setObjectName("edit_btn")
        self.del_btn = QtWidgets.QPushButton(self.tasaisie_identite_tab)
        self.del_btn.setGeometry(QtCore.QRect(1039, 360, 191, 41))
        self.del_btn.setStyleSheet("QPushButton{\n"
"    background-color:  orange;\n"
"    border-radius: 3px;\n"
"    color: white;\n"
"    border: 1px inset gray;\n"
"    font: 16pt \"Century Gothic\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 193, 7);\n"
"    border-radius: 3px;\n"
"    border: 1px inset gray;\n"
"    color: black;\n"
"    font: 16pt \"Century Gothic\";\n"
"}")
        self.del_btn.setObjectName("del_btn")
        self.line = QtWidgets.QFrame(self.tasaisie_identite_tab)
        self.line.setGeometry(QtCore.QRect(-20, 345, 1291, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Recherche = QtWidgets.QLabel(self.tasaisie_identite_tab)
        self.Recherche.setGeometry(QtCore.QRect(130, 4, 286, 40))
        self.Recherche.setStyleSheet("font: 10pt \"Century Gothic\";\n"
"color: rgb(51, 51, 51);")
        self.Recherche.setObjectName("Recherche")
        self.search_lineEdit_2 = QtWidgets.QLineEdit(self.tasaisie_identite_tab)
        self.search_lineEdit_2.setEnabled(True)
        self.search_lineEdit_2.setGeometry(QtCore.QRect(418, 4, 540, 40))
        self.search_lineEdit_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(131, 171, 240);\n"
"")
        self.search_lineEdit_2.setObjectName("search_lineEdit_2")
        self.search_btn_2 = QtWidgets.QPushButton(self.tasaisie_identite_tab)
        self.search_btn_2.setEnabled(True)
        self.search_btn_2.setGeometry(QtCore.QRect(974, 4, 120, 40))
        self.search_btn_2.setObjectName("search_btn_2")
        self.erase_all_widgets_btn = QtWidgets.QPushButton(self.tasaisie_identite_tab)
        self.erase_all_widgets_btn.setGeometry(QtCore.QRect(1109, 4, 120, 40))
        self.erase_all_widgets_btn.setObjectName("erase_all_widgets_btn")
        self.line_3 = QtWidgets.QFrame(self.tasaisie_identite_tab)
        self.line_3.setGeometry(QtCore.QRect(-14, 310, 1281, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.id_content_lbl = QtWidgets.QLabel(self.tasaisie_identite_tab)
        self.id_content_lbl.setGeometry(QtCore.QRect(240, 360, 131, 31))
        self.id_content_lbl.setStyleSheet("border: 1px solid transparent;\n"
"color: transparent;")
        self.id_content_lbl.setText("")
        self.id_content_lbl.setObjectName("id_content_lbl")
        self.label_ID_Enr = QtWidgets.QLabel(self.tasaisie_identite_tab)
        self.label_ID_Enr.setGeometry(QtCore.QRect(380, 360, 111, 31))
        self.label_ID_Enr.setStyleSheet("border: 1px solid transparent;\n"
"color: transparent;")
        self.label_ID_Enr.setText("")
        self.label_ID_Enr.setObjectName("label_ID_Enr")
        self.label_ID_Recup = QtWidgets.QLabel(self.tasaisie_identite_tab)
        self.label_ID_Recup.setGeometry(QtCore.QRect(43, 3, 71, 41))
        self.label_ID_Recup.setStyleSheet("background-color: rgb(0, 1, 146);\n"
"color: rgb(186, 209, 248);\n"
"font: 75 16pt \"Century Gothic\";\n"
"padding-left:5px;")
        self.label_ID_Recup.setObjectName("label_ID_Recup")
        self.attention_lbl = QtWidgets.QLabel(self.tasaisie_identite_tab)
        self.attention_lbl.setGeometry(QtCore.QRect(-3, 391, 390, 31))
        self.attention_lbl.setStyleSheet("border: 1px solid transparent;")
        self.attention_lbl.setText("")
        self.attention_lbl.setObjectName("attention_lbl")
        self.result_label = QtWidgets.QLabel(self.tasaisie_identite_tab)
        self.result_label.setGeometry(QtCore.QRect(410, 393, 351, 31))
        self.result_label.setStyleSheet("border: 0px solid transparent;\n"
"color: transparent;")
        self.result_label.setText("")
        self.result_label.setObjectName("result_label")
        self.line_6 = QtWidgets.QFrame(self.tasaisie_identite_tab)
        self.line_6.setGeometry(QtCore.QRect(-15, 37, 1291, 20))
        self.line_6.setStyleSheet("")
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.id_lbl.raise_()
        self.gridLayoutWidget_2.raise_()
        self.first_btn.raise_()
        self.previous_btn.raise_()
        self.last_btn.raise_()
        self.next_btn.raise_()
        self.add_btn.raise_()
        self.edit_btn.raise_()
        self.del_btn.raise_()
        self.Recherche.raise_()
        self.search_lineEdit_2.raise_()
        self.search_btn_2.raise_()
        self.erase_all_widgets_btn.raise_()
        self.line_3.raise_()
        self.line.raise_()
        self.id_content_lbl.raise_()
        self.label_ID_Enr.raise_()
        self.label_ID_Recup.raise_()
        self.attention_lbl.raise_()
        self.result_label.raise_()
        self.line_6.raise_()
        self.tw_identity.addTab(self.tasaisie_identite_tab, "")
        self.saisie_diagnostic_tab = QtWidgets.QWidget()
        self.saisie_diagnostic_tab.setObjectName("saisie_diagnostic_tab")
        self.symptom_lbl = QtWidgets.QLabel(self.saisie_diagnostic_tab)
        self.symptom_lbl.setGeometry(QtCore.QRect(10, 45, 161, 21))
        self.symptom_lbl.setStyleSheet("font: 12pt \"Century Gothic\";\n"
"color: rgb(51, 51, 51);")
        self.symptom_lbl.setObjectName("symptom_lbl")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.saisie_diagnostic_tab)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 65, 1220, 42))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.temp_lbl = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.temp_lbl.setStyleSheet("font: 12pt \"Century Gothic\";\n"
"color: rgb(51, 51, 51);\n"
"padding-left: 10px;")
        self.temp_lbl.setObjectName("temp_lbl")
        self.horizontalLayout_2.addWidget(self.temp_lbl)
        self.temp_ledit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.temp_ledit.setStyleSheet("\n"
"    background-color: rgb(186, 209, 248);")
        self.temp_ledit.setInputMask("")
        self.temp_ledit.setObjectName("temp_ledit")
        self.horizontalLayout_2.addWidget(self.temp_ledit)
        self.tabd_lbl = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.tabd_lbl.setStyleSheet("font: 12pt \"Century Gothic\";\n"
"color: rgb(51, 51, 51);\n"
"padding-left: 10px;")
        self.tabd_lbl.setObjectName("tabd_lbl")
        self.horizontalLayout_2.addWidget(self.tabd_lbl)
        self.tabd_ledit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.tabd_ledit.setStyleSheet("\n"
"    background-color: rgb(186, 209, 248);")
        self.tabd_ledit.setInputMask("")
        self.tabd_ledit.setObjectName("tabd_ledit")
        self.horizontalLayout_2.addWidget(self.tabd_ledit)
        self.tabg_lbl = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.tabg_lbl.setStyleSheet("font: 12pt \"Century Gothic\";\n"
"color: rgb(51, 51, 51);\n"
"padding-left: 10px;")
        self.tabg_lbl.setObjectName("tabg_lbl")
        self.horizontalLayout_2.addWidget(self.tabg_lbl)
        self.tabg_ledit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.tabg_ledit.setStyleSheet("\n"
"    background-color: rgb(186, 209, 248);")
        self.tabg_ledit.setInputMask("")
        self.tabg_ledit.setObjectName("tabg_ledit")
        self.horizontalLayout_2.addWidget(self.tabg_ledit)
        self.bg_lbl = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.bg_lbl.setStyleSheet("font: 12pt \"Century Gothic\";\n"
"color: rgb(51, 51, 51);\n"
"padding-left: 10px;")
        self.bg_lbl.setObjectName("bg_lbl")
        self.horizontalLayout_2.addWidget(self.bg_lbl)
        self.bg_ledit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.bg_ledit.setStyleSheet("\n"
"    background-color: rgb(186, 209, 248);")
        self.bg_ledit.setInputMask("")
        self.bg_ledit.setObjectName("bg_ledit")
        self.horizontalLayout_2.addWidget(self.bg_ledit)
        self.weight_lbl = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.weight_lbl.setStyleSheet("font: 12pt \"Century Gothic\";\n"
"color: rgb(51, 51, 51);\n"
"padding-left: 10px;")
        self.weight_lbl.setObjectName("weight_lbl")
        self.horizontalLayout_2.addWidget(self.weight_lbl)
        self.weight_ledit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.weight_ledit.setStyleSheet("\n"
"    background-color: rgb(186, 209, 248);")
        self.weight_ledit.setInputMask("")
        self.weight_ledit.setObjectName("weight_ledit")
        self.horizontalLayout_2.addWidget(self.weight_ledit)
        self.record_id_2 = QtWidgets.QLabel(self.saisie_diagnostic_tab)
        self.record_id_2.setGeometry(QtCore.QRect(550, 360, 61, 40))
        self.record_id_2.setStyleSheet("/*background-color: rgb(0, 1, 146);\n"
"color: rgb(186, 209, 248);\n"
"font: 75 16pt \"Century Gothic\";\n"
"padding-left:5px;*/\n"
"\n"
"color: transparent;")
        self.record_id_2.setObjectName("record_id_2")
        self.id_lbl_2 = QtWidgets.QLabel(self.saisie_diagnostic_tab)
        self.id_lbl_2.setGeometry(QtCore.QRect(11, 4, 34, 40))
        self.id_lbl_2.setStyleSheet("font: 12pt \"Century Gothic\";\n"
"font-weight: bold;\n"
"color: rgb(51, 51, 51);\n"
"padding-left: 10px;")
        self.id_lbl_2.setObjectName("id_lbl_2")
        self.previous_btn_2 = QtWidgets.QPushButton(self.saisie_diagnostic_tab)
        self.previous_btn_2.setGeometry(QtCore.QRect(62, 359, 51, 31))
        self.previous_btn_2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 1, 146);\n"
"    border-radius: 3px;\n"
"    color: rgb(186, 209, 24);\n"
"    border: 1px outset gray;\n"
"    font: 12pt \"Century Gothic\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: orange;\n"
"    border-radius: 3px;\n"
"    border: 1px outset gray;\n"
"    font: 12pt \"Century Gothic\";\n"
"}\n"
"")
        self.previous_btn_2.setObjectName("previous_btn_2")
        self.first_btn_2 = QtWidgets.QPushButton(self.saisie_diagnostic_tab)
        self.first_btn_2.setGeometry(QtCore.QRect(10, 359, 51, 31))
        self.first_btn_2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 1, 146);\n"
"    border-radius: 3px;\n"
"    color: rgb(186, 209, 24);\n"
"    border: 1px outset gray;\n"
"    font: 12pt \"Century Gothic\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: orange;\n"
"    border-radius: 3px;\n"
"    border: 1px outset gray;\n"
"    font: 12pt \"Century Gothic\";\n"
"}\n"
"")
        self.first_btn_2.setObjectName("first_btn_2")
        self.last_btn_2 = QtWidgets.QPushButton(self.saisie_diagnostic_tab)
        self.last_btn_2.setGeometry(QtCore.QRect(182, 360, 51, 31))
        self.last_btn_2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 1, 146);\n"
"    border-radius: 3px;\n"
"    color: rgb(186, 209, 24);\n"
"    border: 1px outset gray;\n"
"    font: 12pt \"Century Gothic\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: orange;\n"
"    border-radius: 3px;\n"
"    border: 1px outset gray;\n"
"    font: 12pt \"Century Gothic\";\n"
"}\n"
"")
        self.last_btn_2.setObjectName("last_btn_2")
        self.next_btn_2 = QtWidgets.QPushButton(self.saisie_diagnostic_tab)
        self.next_btn_2.setGeometry(QtCore.QRect(130, 360, 51, 31))
        self.next_btn_2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 1, 146);\n"
"    border-radius: 3px;\n"
"    color: rgb(186, 209, 24);\n"
"    border: 1px outset gray;\n"
"    font: 12pt \"Century Gothic\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: orange;\n"
"    border-radius: 3px;\n"
"    border: 1px outset gray;\n"
"    font: 12pt \"Century Gothic\";\n"
"}\n"
"")
        self.next_btn_2.setObjectName("next_btn_2")
        self.line_2 = QtWidgets.QFrame(self.saisie_diagnostic_tab)
        self.line_2.setGeometry(QtCore.QRect(-3, 345, 1251, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.add_btn_2 = QtWidgets.QPushButton(self.saisie_diagnostic_tab)
        self.add_btn_2.setGeometry(QtCore.QRect(639, 360, 191, 41))
        self.add_btn_2.setStyleSheet("QPushButton{\n"
"    background-color:  rgb(25,135,84);\n"
"    border-radius: 3px;\n"
"    color: white;\n"
"    border: 1px inset gray;\n"
"    font: 16pt \"Century Gothic\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #adc4ad;\n"
"    border-radius: 3px;\n"
"    border: 1px inset gray;\n"
"    color: black;\n"
"    font: 16pt \"Century Gothic\";\n"
"}")
        self.add_btn_2.setObjectName("add_btn_2")
        self.edit_btn_2 = QtWidgets.QPushButton(self.saisie_diagnostic_tab)
        self.edit_btn_2.setGeometry(QtCore.QRect(839, 360, 191, 41))
        self.edit_btn_2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(13,110,253);\n"
"    border-radius: 3px;\n"
"    color: white;\n"
"    border: 1px inset gray;\n"
"    font: 16pt \"Century Gothic\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(13,202,240);\n"
"    border-radius: 3px;\n"
"    border: 1px inset gray;\n"
"    color: black;\n"
"    font: 16pt \"Century Gothic\";\n"
"}")
        self.edit_btn_2.setObjectName("edit_btn_2")
        self.del_btn_2 = QtWidgets.QPushButton(self.saisie_diagnostic_tab)
        self.del_btn_2.setGeometry(QtCore.QRect(1039, 360, 191, 41))
        self.del_btn_2.setStyleSheet("QPushButton{\n"
"    background-color:  orange;\n"
"    border-radius: 3px;\n"
"    color: white;\n"
"    border: 1px inset gray;\n"
"    font: 16pt \"Century Gothic\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 193, 7);\n"
"    border-radius: 3px;\n"
"    border: 1px inset gray;\n"
"    color: black;\n"
"    font: 16pt \"Century Gothic\";\n"
"}")
        self.del_btn_2.setObjectName("del_btn_2")
        self.id_content_lbl_2 = QtWidgets.QLabel(self.saisie_diagnostic_tab)
        self.id_content_lbl_2.setGeometry(QtCore.QRect(250, 360, 211, 31))
        self.id_content_lbl_2.setStyleSheet("border: 1px solid transparent;")
        self.id_content_lbl_2.setText("")
        self.id_content_lbl_2.setObjectName("id_content_lbl_2")
        self.label_ID_Recup_2 = QtWidgets.QLabel(self.saisie_diagnostic_tab)
        self.label_ID_Recup_2.setGeometry(QtCore.QRect(43, 3, 71, 41))
        self.label_ID_Recup_2.setStyleSheet("background-color: rgb(0, 1, 146);\n"
"color: rgb(186, 209, 248);\n"
"font: 75 16pt \"Century Gothic\";\n"
"padding-left:5px;")
        self.label_ID_Recup_2.setObjectName("label_ID_Recup_2")
        self.layoutWidget = QtWidgets.QWidget(self.saisie_diagnostic_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 110, 1221, 241))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.diagnostic_lbl = QtWidgets.QLabel(self.layoutWidget)
        self.diagnostic_lbl.setStyleSheet("font: 12pt \"Century Gothic\";\n"
"color: rgb(51, 51, 51);")
        self.diagnostic_lbl.setObjectName("diagnostic_lbl")
        self.gridLayout.addWidget(self.diagnostic_lbl, 0, 0, 1, 1)
        self.treatments_lbl = QtWidgets.QLabel(self.layoutWidget)
        self.treatments_lbl.setStyleSheet("font: 12pt \"Century Gothic\";\n"
"color: rgb(51, 51, 51);")
        self.treatments_lbl.setObjectName("treatments_lbl")
        self.gridLayout.addWidget(self.treatments_lbl, 0, 1, 1, 1)
        self.diagnostic_textEdit = QtWidgets.QTextEdit(self.layoutWidget)
        self.diagnostic_textEdit.setStyleSheet("\n"
"    background-color: rgb(186, 209, 248);")
        self.diagnostic_textEdit.setObjectName("diagnostic_textEdit")
        self.gridLayout.addWidget(self.diagnostic_textEdit, 1, 0, 1, 1)
        self.treatments_textEdit = QtWidgets.QTextEdit(self.layoutWidget)
        self.treatments_textEdit.setStyleSheet("\n"
"    background-color: rgb(186, 209, 248);")
        self.treatments_textEdit.setObjectName("treatments_textEdit")
        self.gridLayout.addWidget(self.treatments_textEdit, 1, 1, 3, 1)
        self.observeations_lbl = QtWidgets.QLabel(self.layoutWidget)
        self.observeations_lbl.setStyleSheet("font: 12pt \"Century Gothic\";\n"
"color: rgb(51, 51, 51);")
        self.observeations_lbl.setObjectName("observeations_lbl")
        self.gridLayout.addWidget(self.observeations_lbl, 2, 0, 1, 1)
        self.observations_textEdit = QtWidgets.QTextEdit(self.layoutWidget)
        self.observations_textEdit.setStyleSheet("\n"
"    background-color: rgb(186, 209, 248);")
        self.observations_textEdit.setObjectName("observations_textEdit")
        self.gridLayout.addWidget(self.observations_textEdit, 3, 0, 1, 1)
        self.attention_lbl_2 = QtWidgets.QLabel(self.saisie_diagnostic_tab)
        self.attention_lbl_2.setGeometry(QtCore.QRect(-3, 391, 390, 31))
        self.attention_lbl_2.setStyleSheet("border: 1px solid transparent;")
        self.attention_lbl_2.setText("")
        self.attention_lbl_2.setObjectName("attention_lbl_2")
        self.erase_all_widgets_btn_2 = QtWidgets.QPushButton(self.saisie_diagnostic_tab)
        self.erase_all_widgets_btn_2.setGeometry(QtCore.QRect(1109, 4, 120, 40))
        self.erase_all_widgets_btn_2.setObjectName("erase_all_widgets_btn_2")
        self.line_7 = QtWidgets.QFrame(self.saisie_diagnostic_tab)
        self.line_7.setGeometry(QtCore.QRect(0, 37, 1291, 20))
        self.line_7.setStyleSheet("")
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.tw_identity.addTab(self.saisie_diagnostic_tab, "")
        self.quit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.quit_btn.setGeometry(QtCore.QRect(1049, 620, 191, 41))
        self.quit_btn.setStyleSheet("QPushButton{\n"
"    background-color:  rgb(220, 53, 69);\n"
"    border-radius: 3px;\n"
"    color: white;\n"
"    border: 1px inset gray;\n"
"    font: 16pt \"Century Gothic\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #ff9c8a;\n"
"    border-radius: 3px;\n"
"    border: 1px inset gray;\n"
"    color: black;\n"
"    font: 16pt \"Century Gothic\";\n"
"}")
        self.quit_btn.setObjectName("quit_btn")
        self.label_date_heure_recup = QtWidgets.QLabel(self.centralwidget)
        self.label_date_heure_recup.setGeometry(QtCore.QRect(420, 626, 391, 31))
        self.label_date_heure_recup.setStyleSheet("border: 1px solid transparent;")
        self.label_date_heure_recup.setText("")
        self.label_date_heure_recup.setObjectName("label_date_heure_recup")
        self.infos_csmcg_lbl_2 = QtWidgets.QLabel(self.centralwidget)
        self.infos_csmcg_lbl_2.setGeometry(QtCore.QRect(-2, 662, 1271, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat,Roboto,Lato,Poppins,Oswald,Raleway,Arial,sans-serif,Verdana,sans-serif")
        font.setBold(False)
        font.setWeight(50)
        self.infos_csmcg_lbl_2.setFont(font)
        self.infos_csmcg_lbl_2.setStyleSheet("font-family: \"Montserrat\", Roboto, Lato, Poppins, Oswald, Raleway, \"Arial\", sans-serif, \"Verdana\", sans-serif;\n"
"color: #000;\n"
"text-shadow: -1px -1px 3px #888; /* Ombre externe claire */\n"
"")
        self.infos_csmcg_lbl_2.setAlignment(QtCore.Qt.AlignCenter)
        self.infos_csmcg_lbl_2.setObjectName("infos_csmcg_lbl_2")
        self.line_bas = QtWidgets.QFrame(self.centralwidget)
        self.line_bas.setGeometry(QtCore.QRect(-10, 656, 1291, 20))
        self.line_bas.setStyleSheet("")
        self.line_bas.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_bas.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_bas.setObjectName("line_bas")
        self.line_bas_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_bas_2.setGeometry(QtCore.QRect(0, 694, 1281, 20))
        self.line_bas_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_bas_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_bas_2.setObjectName("line_bas_2")
        self.infos_csmcg_lbl = QtWidgets.QLabel(self.centralwidget)
        self.infos_csmcg_lbl.setGeometry(QtCore.QRect(-2, 677, 1271, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat,Roboto,Lato,Poppins,Oswald,Raleway,Arial,sans-serif,Verdana,sans-serif")
        self.infos_csmcg_lbl.setFont(font)
        self.infos_csmcg_lbl.setStyleSheet("font-family: \"Montserrat\", Roboto, Lato, Poppins, Oswald, Raleway, \"Arial\", sans-serif, \"Verdana\", sans-serif;\n"
"color: #000;\n"
"text-shadow: -1px -1px 3px #888; /* Ombre externe claire */")
        self.infos_csmcg_lbl.setLineWidth(1)
        self.infos_csmcg_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.infos_csmcg_lbl.setIndent(-1)
        self.infos_csmcg_lbl.setObjectName("infos_csmcg_lbl")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(-2, 86, 1271, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_bas_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_bas_3.setGeometry(QtCore.QRect(-2, 700, 1291, 20))
        self.line_bas_3.setStyleSheet("")
        self.line_bas_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_bas_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_bas_3.setObjectName("line_bas_3")
        dashboard_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(dashboard_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1266, 23))
        self.menubar.setObjectName("menubar")
        dashboard_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(dashboard_window)
        self.statusbar.setObjectName("statusbar")
        dashboard_window.setStatusBar(self.statusbar)

        self.retranslateUi(dashboard_window)
        self.tw_identity.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(dashboard_window)
        dashboard_window.setTabOrder(self.tw_identity, self.search_lineEdit)
        dashboard_window.setTabOrder(self.search_lineEdit, self.restitute_tbl)
        dashboard_window.setTabOrder(self.restitute_tbl, self.refresh_btn)
        dashboard_window.setTabOrder(self.refresh_btn, self.search_lineEdit_2)
        dashboard_window.setTabOrder(self.search_lineEdit_2, self.search_btn_2)
        dashboard_window.setTabOrder(self.search_btn_2, self.erase_all_widgets_btn)
        dashboard_window.setTabOrder(self.erase_all_widgets_btn, self.name_ledit)
        dashboard_window.setTabOrder(self.name_ledit, self.commune_ledit)
        dashboard_window.setTabOrder(self.commune_ledit, self.profession_ledit)
        dashboard_window.setTabOrder(self.profession_ledit, self.sector_spinBox)
        dashboard_window.setTabOrder(self.sector_spinBox, self.age_spinBox)
        dashboard_window.setTabOrder(self.age_spinBox, self.phone_ledit)
        dashboard_window.setTabOrder(self.phone_ledit, self.woman_rbtn)
        dashboard_window.setTabOrder(self.woman_rbtn, self.man_rbtn)
        dashboard_window.setTabOrder(self.man_rbtn, self.zone_comboBox)
        dashboard_window.setTabOrder(self.zone_comboBox, self.temp_ledit)
        dashboard_window.setTabOrder(self.temp_ledit, self.tabd_ledit)
        dashboard_window.setTabOrder(self.tabd_ledit, self.tabg_ledit)
        dashboard_window.setTabOrder(self.tabg_ledit, self.bg_ledit)
        dashboard_window.setTabOrder(self.bg_ledit, self.weight_ledit)
        dashboard_window.setTabOrder(self.weight_ledit, self.diagnostic_textEdit)
        dashboard_window.setTabOrder(self.diagnostic_textEdit, self.treatments_textEdit)
        dashboard_window.setTabOrder(self.treatments_textEdit, self.observations_textEdit)
        dashboard_window.setTabOrder(self.observations_textEdit, self.first_btn_2)
        dashboard_window.setTabOrder(self.first_btn_2, self.previous_btn_2)
        dashboard_window.setTabOrder(self.previous_btn_2, self.next_btn_2)
        dashboard_window.setTabOrder(self.next_btn_2, self.last_btn_2)
        dashboard_window.setTabOrder(self.last_btn_2, self.add_btn_2)
        dashboard_window.setTabOrder(self.add_btn_2, self.edit_btn_2)
        dashboard_window.setTabOrder(self.edit_btn_2, self.del_btn_2)
        dashboard_window.setTabOrder(self.del_btn_2, self.quit_btn)
        dashboard_window.setTabOrder(self.quit_btn, self.date_heure)
        dashboard_window.setTabOrder(self.date_heure, self.del_btn)
        dashboard_window.setTabOrder(self.del_btn, self.previous_btn)
        dashboard_window.setTabOrder(self.previous_btn, self.add_btn)
        dashboard_window.setTabOrder(self.add_btn, self.edit_btn)
        dashboard_window.setTabOrder(self.edit_btn, self.last_btn)
        dashboard_window.setTabOrder(self.last_btn, self.next_btn)
        dashboard_window.setTabOrder(self.next_btn, self.first_btn)

    def retranslateUi(self, dashboard_window):
        _translate = QtCore.QCoreApplication.translate
        dashboard_window.setWindowTitle(_translate("dashboard_window", "Cabinet de Soins Médicaux la Croix Glorieuse"))
        self.header_lbl_2.setText(_translate("dashboard_window", "<html><head/><body><p align=\"center\">Cabinet de Soins Médicaux <span style=\" font-weight:600;\">LA CROIX GLORIEUSE</span></p></body></html>"))
        self.user_auth_lbl.setText(_translate("dashboard_window", "Utilisateur authentifié :"))
        item = self.restitute_tbl.horizontalHeaderItem(0)
        item.setText(_translate("dashboard_window", "N°"))
        item = self.restitute_tbl.horizontalHeaderItem(1)
        item.setText(_translate("dashboard_window", "Nom & Prénoms"))
        item = self.restitute_tbl.horizontalHeaderItem(2)
        item.setText(_translate("dashboard_window", "Profession"))
        item = self.restitute_tbl.horizontalHeaderItem(3)
        item.setText(_translate("dashboard_window", "Sexe"))
        item = self.restitute_tbl.horizontalHeaderItem(4)
        item.setText(_translate("dashboard_window", "Age"))
        item = self.restitute_tbl.horizontalHeaderItem(5)
        item.setText(_translate("dashboard_window", "Commune"))
        item = self.restitute_tbl.horizontalHeaderItem(6)
        item.setText(_translate("dashboard_window", "Secteur"))
        item = self.restitute_tbl.horizontalHeaderItem(7)
        item.setText(_translate("dashboard_window", "Téléphone"))
        item = self.restitute_tbl.horizontalHeaderItem(8)
        item.setText(_translate("dashboard_window", "Zone de résidence (en Km)"))
        item = self.restitute_tbl.horizontalHeaderItem(9)
        item.setText(_translate("dashboard_window", "T°"))
        item = self.restitute_tbl.horizontalHeaderItem(10)
        item.setText(_translate("dashboard_window", "TA BD"))
        item = self.restitute_tbl.horizontalHeaderItem(11)
        item.setText(_translate("dashboard_window", "TA BG"))
        item = self.restitute_tbl.horizontalHeaderItem(12)
        item.setText(_translate("dashboard_window", "BG"))
        item = self.restitute_tbl.horizontalHeaderItem(13)
        item.setText(_translate("dashboard_window", "Poids"))
        item = self.restitute_tbl.horizontalHeaderItem(14)
        item.setText(_translate("dashboard_window", "Diagnostic"))
        item = self.restitute_tbl.horizontalHeaderItem(15)
        item.setText(_translate("dashboard_window", "Traitements"))
        item = self.restitute_tbl.horizontalHeaderItem(16)
        item.setText(_translate("dashboard_window", "Observations"))
        item = self.restitute_tbl.horizontalHeaderItem(17)
        item.setText(_translate("dashboard_window", "Date et Heure"))
        self.refresh_btn.setText(_translate("dashboard_window", "Rafraichir"))
        self.manage_users_btn.setText(_translate("dashboard_window", "Gestion Utilisateurs"))
        self.search_lbl.setText(_translate("dashboard_window", "Recherche de Noms dans la base de données"))
        self.search_btn.setText(_translate("dashboard_window", "Actualiser"))
        self.tw_identity.setTabText(self.tw_identity.indexOf(self.patient_tab), _translate("dashboard_window", "Informations de Tous les Patients"))
        self.id_lbl.setText(_translate("dashboard_window", "ID"))
        self.phone_lbl.setText(_translate("dashboard_window", "Téléphone"))
        self.sector_lbl.setText(_translate("dashboard_window", "Secteur"))
        self.profession_lbl.setText(_translate("dashboard_window", "Profession"))
        self.commune_lbl.setText(_translate("dashboard_window", "Commune"))
        self.age_lbl.setText(_translate("dashboard_window", "Age"))
        self.woman_rbtn.setText(_translate("dashboard_window", "Féminin"))
        self.gender_lbl.setText(_translate("dashboard_window", "Sexe"))
        self.zone_comboBox.setItemText(0, _translate("dashboard_window", "Choisir la distance du domicile en Km"))
        self.zone_comboBox.setItemText(1, _translate("dashboard_window", "0-4"))
        self.zone_comboBox.setItemText(2, _translate("dashboard_window", "5-9"))
        self.zone_comboBox.setItemText(3, _translate("dashboard_window", "10 et plus"))
        self.zone_lbl.setText(_translate("dashboard_window", "<div>Zone de résidence</div><div> (en Km)</div>"))
        self.name_lbl.setText(_translate("dashboard_window", "Nom & Prénoms"))
        self.man_rbtn.setText(_translate("dashboard_window", "Masculin"))
        self.record_id.setText(_translate("dashboard_window", "0"))
        self.first_btn.setText(_translate("dashboard_window", "<<"))
        self.previous_btn.setText(_translate("dashboard_window", "<"))
        self.last_btn.setText(_translate("dashboard_window", ">>"))
        self.next_btn.setText(_translate("dashboard_window", ">"))
        self.add_btn.setText(_translate("dashboard_window", "Ajouter"))
        self.edit_btn.setText(_translate("dashboard_window", "Modifier"))
        self.del_btn.setText(_translate("dashboard_window", "supprimer"))
        self.Recherche.setText(_translate("dashboard_window", "Recherche pa Nom dans la Base de Donnée"))
        self.search_btn_2.setText(_translate("dashboard_window", "Rechercher"))
        self.erase_all_widgets_btn.setText(_translate("dashboard_window", "Effacer tout"))
        self.label_ID_Recup.setText(_translate("dashboard_window", "0"))
        self.tw_identity.setTabText(self.tw_identity.indexOf(self.tasaisie_identite_tab), _translate("dashboard_window", "Saisie Informations Identitaires et Résidentielles des Patients"))
        self.symptom_lbl.setText(_translate("dashboard_window", "Symptômes"))
        self.temp_lbl.setText(_translate("dashboard_window", "T°"))
        self.temp_ledit.setText(_translate("dashboard_window", "0"))
        self.tabd_lbl.setText(_translate("dashboard_window", "TA BD"))
        self.tabd_ledit.setText(_translate("dashboard_window", "0"))
        self.tabg_lbl.setText(_translate("dashboard_window", "TA BG"))
        self.tabg_ledit.setText(_translate("dashboard_window", "0"))
        self.bg_lbl.setText(_translate("dashboard_window", "BG"))
        self.bg_ledit.setText(_translate("dashboard_window", "0"))
        self.weight_lbl.setText(_translate("dashboard_window", "Poids"))
        self.weight_ledit.setText(_translate("dashboard_window", "0"))
        self.record_id_2.setText(_translate("dashboard_window", "0"))
        self.id_lbl_2.setText(_translate("dashboard_window", "ID"))
        self.previous_btn_2.setText(_translate("dashboard_window", "<"))
        self.first_btn_2.setText(_translate("dashboard_window", "<<"))
        self.last_btn_2.setText(_translate("dashboard_window", ">>"))
        self.next_btn_2.setText(_translate("dashboard_window", ">"))
        self.add_btn_2.setText(_translate("dashboard_window", "Ajouter"))
        self.edit_btn_2.setText(_translate("dashboard_window", "Modifier"))
        self.del_btn_2.setText(_translate("dashboard_window", "supprimer"))
        self.label_ID_Recup_2.setText(_translate("dashboard_window", "0"))
        self.diagnostic_lbl.setText(_translate("dashboard_window", "Diagnostic"))
        self.treatments_lbl.setText(_translate("dashboard_window", "Traitements"))
        self.observeations_lbl.setText(_translate("dashboard_window", "Observations"))
        self.erase_all_widgets_btn_2.setText(_translate("dashboard_window", "Effacer tout"))
        self.tw_identity.setTabText(self.tw_identity.indexOf(self.saisie_diagnostic_tab), _translate("dashboard_window", "Diagnostic des Patients"))
        self.quit_btn.setText(_translate("dashboard_window", "Quitter"))
        self.infos_csmcg_lbl_2.setText(_translate("dashboard_window", "Cabinet de Soins Médicaux \"LA CROIX GLORIEUSE\" "))
        self.infos_csmcg_lbl.setText(_translate("dashboard_window", "Cabinet de Soins Médicaux \"LA CROIX GLORIEUSE\" Secteur 16 - Song Naba - 05 bp 6592 Ouagadougou - Tél. +226 70 27 05 02 / 77 25 76 65 - Email : santeglorieuse@yahoo.fr"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dashboard_window = QtWidgets.QMainWindow()
    ui = Ui_dashboard_window()
    ui.setupUi(dashboard_window)
    dashboard_window.show()
    sys.exit(app.exec_())
